server:
  port: 8081

spring:
  application:
    name: milktea-backend
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/milktea_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: 13603994106
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      hibernate.format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
    datatype:
      hibernate5:
        enabled: true
  flyway:
    enabled: false

jwt:
  secret: "your-secret-key-that-is-at-least-32-bytes-long-here!"
  expiration: 86400000

websocket:
  allowed-origins: "*"
  endpoint: /ws
  broker-prefix: /topic
  app-destination-prefix: /app

logging:
  level:
    com.milktea.app: DEBUG
    org.springframework.security: DEBUG

file:
  upload-dir: uploads
  max-size-mb: 5
  supported-image-types: image/jpeg,image/png,image/gif

amap:
  key: ${AMAP_KEY:your-amap-api-key-here}
  regeo-url: https://restapi.amap.com/v3/geocode/regeo

alipay:
  app-id: 2021000117650001
  app-private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDQD7EUSsTvals8tc1f4OSZt0nHYpDS/x6yPXq9/rYbhbarB7/r4QcjTS60hsHqtG6o6mjif3zHKGD3VI6E7diVDNktsZ/H/4sZB+OmfL9vYzPY6bFlSHqcgHyE/y6S/BnV6EP5B/jTuJWdJvLZnQbM++j0tuOMOUZ+aBUI3yhurpUDYJ6Kb+X6RAItPdhtY9x0vpEmrTrfFIWf76ekUsT4k6zfXtA+BMJGrPzN7VIx5OCU5VINVefIag8B5NbXetM74GHM2bBeKaGs4YZglqnq51Br8LKg6TDKq3IgFqWqyFZskIOlsXe0Z7IOxjVfLaHXMmx4yysv5OPoenBPmqaHAgMBAAECggEBAJbpytedJBtEWck/VSgmR6n3eFxW8hUZV3qRfWYySoTMCCMmC99b6YGBik8HL8C9/0YmQM2JC0ip0SuU+YsRufbiyuSJ4gt/H7WYM1efRHvWyNSdLT75w3Wg/LC7J10V3ud5AVSwo5tuV5cVmTCe5T/puJ9HyOT85lTpydgVhY5BZKZUNz2YbZquonAV61htKRKRsi2fGZA8hF8qN/qx/gTuRHp5J3fVGmg6J3zIvguesPLOfGC7qScjD9/DN19STLaUNztFGa3sQS9xE10UtngOVGX9NQU5ojtZj7k1dPhVQ4eTn+2x+2Z64k8Cun36Baql6QDxaOxlOMU2RryOtYECgYEA58lKPPI8DSP4aMhxAXwXcN2bUAN6zTjaM3N6NAtVbsJ4TzEL39H3LThV+bAsXcuZacCFEui18Dk1rNt1h/bUQwqptdZhCpvbMAMvuQwE/DAwqfXKC+UedH0kfAGGmekmKDlsWh1gncujRAtnDPgg8HHcbPWAMv79dYvmx1LcpwsCgYEA5cvrT6mGE1PGDpY271YnRkgmwv5lqJczv16devtAadHqX3GA2vYcId23sTiM2hhrBP7x9U2CtBN9gDT68foEgX8ERrhdeny9AAhhDJYZHOa39jpt2f1JGfBRZHvERcIYbEGqMlB4RDFfIxTWGi5p/czYbyW/EYkl9cJCFRxV+/UCgYB8+UNV6SYHz8U4ehq0OjxJVrNPSREFZgoAg9r4BMRjm+dSi5djbspfT2jL3/mL+SMWqf8WWvL+O1p9gTa1wJhiLXWj3ZslJTPhh1ZL5/coIrOacDQohbkOBguN8SSqB9PTDGMnk39slUfKgHtnusHH4xx+g0BEPshagLxF7J+cUQKBgGVXRtD86/n+CexI5rUqA2wFScLYujBdbh7JNR4VS9TfFEM/JRprSwDMbMQlMkjEV/3+COqrYibUKZauxrSMFAyf3Vzq1Z69AATRrSsFztFmFl7qaaOnBeQAjYSI6IfzDx4+3zYNMtywAUrRV5J4QZoCCrkJpnevSiRVpRr2Qh05AoGAM9kLfYhj2P4+6ZrXknzngiOC+2gZoQ+I/i/2KTWMcS5xtamX13S4sM6lBt0QfJUB6E1iaS/uySn57QlEbH/gPN1KY0bt2O99zDr3yPGcELeXSITflN8LdqECt2jit1ACczoQUDEPceqgpS0ugusYD+jbtzAyb4z2emOKrWHgb28=
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhn9r4t1adzLI25ZHUdjByiXxRviZ4ZN7DUBB6IMRbaDu44L27cz4ggqqPd6NgMl60IkV9FOff+vzn8BMZZlwjEM9AR4oB4DNJFO/iQdMc/jLKhkKVIsRNjg3iMxdKuLO//KyzeTW+WcedkVz7KLZF7fg4ebeJ8qvRKc/F+UPHk6TqwH6Lz85J7L3Ht3cyg/jCOVc6HXG9fd39JlRW6YTSzhjFeTPG73fKmcfF94qZ/131CmNeEUkIlCW4XQItPPdA07TSwI/2xVN0zqjrMv4YpZ229oC9lLvgF5aBVr6LDwZuwO+4iBbYInnCNcFXh7E0h0MGLiYqfHswteBS4lUfQIDAQAB
  gateway-url: https://openapi.alipay.com/gateway.do
  notify-url: http://your-domain.com/api/v1/app/payment/callback/alipay
  return-url: http://your-domain.com/payment-success
